/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author MATHEUS LIMA
 */
public class TelaBebidas extends javax.swing.JFrame {

    /**
     * Creates new form TelaChocolate
     */
    public TelaBebidas() {
        initComponents();
    }

    public static String nome;
    public static List<String> descricao;
    public static List<String> ingredientes;
    public static double preco;

    public TelaBebidas(String nome, List<String> descricao, List<String> ingredientes, double preco) {
        TelaBebidas.nome = nome;
        TelaBebidas.descricao = descricao;
        TelaBebidas.ingredientes = ingredientes;
        TelaBebidas.preco = preco;

        initComponents();

        this.txtNomeBebida.setEditable(false);
        this.txtDescricaoBebida.setEditable(false);
        this.txtIngredientesBebida.setEditable(false);
        this.txtPrecoBebida.setEditable(false);

        StringBuilder items = new StringBuilder();
        ingredientes.forEach((saida) -> {
            items.append(" - ").append(saida).append("\n");
        });

        StringBuilder itemsdescricao = new StringBuilder();
        descricao.forEach((saida) -> {
            itemsdescricao.append(" ").append(saida).append("\n");
        });

        this.txtNomeBebida.setText(nome);
        this.txtPrecoBebida.setText("R$: " + String.valueOf(preco));
        this.txtIngredientesBebida.setText(items.toString());
        this.txtDescricaoBebida.setText(itemsdescricao.toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricaoBebida = new javax.swing.JTextArea();
        btnConfirmaChocolate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPrecoBebida = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtIngredientesBebida = new javax.swing.JTextArea();
        txtNomeBebida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(480, 380));

        txtDescricaoBebida.setEditable(false);
        txtDescricaoBebida.setColumns(20);
        txtDescricaoBebida.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        txtDescricaoBebida.setForeground(new java.awt.Color(204, 102, 0));
        txtDescricaoBebida.setTabSize(0);
        txtDescricaoBebida.setAutoscrolls(false);
        txtDescricaoBebida.setBorder(null);
        jScrollPane1.setViewportView(txtDescricaoBebida);

        btnConfirmaChocolate.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        btnConfirmaChocolate.setForeground(new java.awt.Color(255, 102, 102));
        btnConfirmaChocolate.setText("Confirma");
        btnConfirmaChocolate.setBorder(null);
        btnConfirmaChocolate.setBorderPainted(false);
        btnConfirmaChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmaChocolateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 102, 0));
        jLabel3.setText("Ingredientes");

        jLabel4.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 102, 0));
        jLabel4.setText("Preço");

        jLabel5.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Descrição");

        txtPrecoBebida.setEditable(false);
        txtPrecoBebida.setFont(new java.awt.Font("Gabriola", 2, 18)); // NOI18N
        txtPrecoBebida.setForeground(new java.awt.Color(153, 51, 0));
        txtPrecoBebida.setBorder(null);
        txtPrecoBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoBebidaActionPerformed(evt);
            }
        });

        txtIngredientesBebida.setEditable(false);
        txtIngredientesBebida.setBackground(new java.awt.Color(255, 255, 255));
        txtIngredientesBebida.setColumns(20);
        txtIngredientesBebida.setForeground(new java.awt.Color(204, 102, 0));
        txtIngredientesBebida.setRows(5);
        txtIngredientesBebida.setBorder(null);
        jScrollPane2.setViewportView(txtIngredientesBebida);

        txtNomeBebida.setFont(new java.awt.Font("Gabriola", 2, 24)); // NOI18N
        txtNomeBebida.setForeground(new java.awt.Color(255, 153, 153));
        txtNomeBebida.setBorder(null);
        txtNomeBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeBebidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(txtNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addComponent(txtPrecoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(btnConfirmaChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(txtNomeBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel5)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConfirmaChocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(157, 157, 157))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmaChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmaChocolateActionPerformed
        // confirmar pedido
        int opc = JOptionPane.showConfirmDialog(rootPane,
                "Você deseja confirmar pedido?",
                "Escolha a opção",
                JOptionPane.YES_NO_OPTION
        );

        if (opc == 0) {
            TelaLanchonete lanchonete = new TelaLanchonete();
            lanchonete.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnConfirmaChocolateActionPerformed

    private void txtPrecoBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoBebidaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPrecoBebidaActionPerformed

    private void txtNomeBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeBebidaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtNomeBebidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBebidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBebidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmaChocolate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescricaoBebida;
    private javax.swing.JTextArea txtIngredientesBebida;
    private javax.swing.JTextField txtNomeBebida;
    private javax.swing.JTextField txtPrecoBebida;
    // End of variables declaration//GEN-END:variables
}
